# Generated by Django 4.1 on 2023-03-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makeAPI", "0002_remove_drink_description_remove_drink_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drink", name="dueDate", field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="drink", name="task", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="drink",
            name="urgency",
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
