# Generated by Django 4.1 on 2023-03-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makeAPI", "0003_alter_drink_duedate_alter_drink_task_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drink", name="urgency", field=models.CharField(max_length=10),
        ),
    ]
