# Generated by Django 4.1 on 2023-03-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makeAPI", "0004_alter_drink_urgency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Completedtasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=100)),
                ("urgency", models.CharField(max_length=10)),
            ],
        ),
    ]
